
[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_title = false
option_as_alt = "Both"
dynamic_padding = true
decorations_theme_variant = "Light"
opacity = 0.95

[colors]
transparent_background_colors = true

[selection]
save_to_clipboard = true

[general]
import = ["./catppuccin/catppuccin-latte.toml"]

